/* Leaf compiler
   Copyright (c) 2023 bellrise */

#include "lc.h"

static void emit_func_preamble(struct emitter *self)
{
    fprintf(self->out, "    push bp\n");
    fprintf(self->out, "    mov bp, sp\n");
}

static void emit_func_epilogue(struct emitter *self)
{
    fprintf(self->out, "    mov sp, bp\n");
    fprintf(self->out, "    pop bp\n");
    fprintf(self->out, "    ret\n");
}

static void emit_func(struct emitter *self, struct block_func *func)
{
    struct block *block;

    fputc('\n', self->out);

    if (func->exported)
        fprintf(self->out, ".export %s\n", func->label);
    fprintf(self->out, "%s:\n", func->label);

    block = func->head.child;
    while (block) {
        switch (block->type) {
        case BLOCK_FUNC_PREAMBLE:
            emit_func_preamble(self);
            break;
        case BLOCK_FUNC_EPILOGUE:
            emit_func_epilogue(self);
            break;
        default:
            die("don't know how to emit %s", block_name(block));
        }

        block = block->next;
    }
}

void emitter_emit(struct emitter *self, const char *path)
{
    struct block *block;

    self->out = fopen(path, "w");
    if (!self->out)
        die("failed to open result file");

    if (self->file_block->type != BLOCK_FILE)
        die("expected BLOCK_FILE in emitter_emit");

    fprintf(self->out, "; Generated by irid-lc\n");

    block = self->file_block->child;
    while (block) {
        if (block->type != BLOCK_FUNC)
            die("only BLOCK_FUNC allowed at file top-level");

        emit_func(self, (struct block_func *) block);
        block = block->next;
    }
}
