; Generated by irid-lc

.org 0

_entry:
    mov sp, 0x8000
    mov bp, 0x8000
    mov r0, 4096
    call iosel
    call main
    call halt
    ret

.export main
main:
    push bp
    push r4
    push r5
    mov bp, sp
    sub sp, 2  ; int a
    mov r4, bp
    sub r4, 2
    mov r5, 4660
    store r5, r4
    mov r4, bp
    sub r4, 2
    load r0, r4
    call putx
    mov sp, bp
    pop r5
    pop r4
    pop bp
    ret

.export other
other:
    push bp
    push r4
    push r5
    mov bp, sp
    sub sp, 2  ; int b
    mov sp, bp
    pop r5
    pop r4
    pop bp
    ret
