#!/usr/bin/python3

# Generate a program that can be loaded into the emulator. The program ends
# with a forced CPU fault, so we can see values stored in the registers.

# mov16 r0, 0x2211
# mov16 sp, 0x4000
# mov bp, sp
# push16 0x1155
# pop r7
# cpucall fault
sprog = b'\x16\x00\x11\x22'         \
        b'\x16\x71\x40\x00'         \
        b'\x14\x72\x71'             \
        b'\x12\x55\x11'             \
        b'\x13\x07'                 \
        b'\x01\x14'

with open('test.bin', 'wb') as f:
    f.write(sprog)
