#!/usr/bin/python3

# Generate a program that can be loaded into the emulator. The program ends
# with a forced CPU fault, so we can see values stored in the registers.

# mov16 r3, 0x1122
# mov16 r0, 0x003e
# store r3, r0
# load h1, r0
# cpucall fault
sprog = b'\x16\x03\x22\x11'         \
		b'\x16\x00\x3e\x00'         \
		b'\x18\x03\x00'             \
		b'\x17\x12\x00'             \
		b'\x01\x14'

with open('test.bin', 'wb') as f:
	f.write(sprog)
