#!/usr/bin/python3

# Generate a program that can be loaded into the emulator. The program ends
# with a forced CPU fault, so we can see values stored in the registers.

# mov16 r0, 0x1122
# mov16 sp, 0x0040
# mov bp, sp
# push r0
# push l0
# cpucall fault
sprog = b'\x16\x00\x11\x22'         \
        b'\x16\x71\x40\x00'         \
        b'\x14\x72\x71'             \
        b'\x10\x00'                 \
        b'\x10\x11'                 \
        b'\x01\x14'

with open('test.bin', 'wb') as f:
    f.write(sprog)
